In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import random

In [3]:
# Set SEED Values
SEED = 42

random.seed(SEED)
tf.random.set_seed(SEED)
np.random.seed(SEED)

In [4]:
# Tensorflow Constants
rank_0_tensor = tf.constant(3)
print(rank_0_tensor)

rank_0_tensor = tf.constant(3.141592654)
print(rank_0_tensor)

rank_0_tensor = tf.constant(3.141592654, dtype=tf.float64)
print(rank_0_tensor)

rank_1_tensor = tf.constant([2.0,3.0,4.0])
print(rank_1_tensor)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(3.1415927, shape=(), dtype=float32)
tf.Tensor(3.141592654, shape=(), dtype=float64)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


### Tensor Terminology
1. Shape: The length of each of the axes in a tensor
1. Rank: The number of tensor axes. A scalar has rank 0, vector has rank 1 
    and matrix has rank 2.
1. Axis or Dimension: The dimension of a tensor
1. Size: The total number of items in a tensor, the product of the shape vector's element. 

In [5]:
# Concatenation in Tensor is similar to NumPy
t1 = tf.constant([[1,2,3],[4,5,6]])
t2 = tf.constant([[7,8,9],[10,11,12]])

print(t1)
print(t2)
print("Concat along axis=0\n")
print(tf.concat([t1,t2],axis=0))
print("\nConcat along axis=1\n")
print(tf.concat([t1,t2], axis=1))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Concat along axis=0

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)

Concat along axis=1

tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


### TensorFlow Variables
Variables in tensorflow can only be asigned using the `assign()`, they can't be assigned using the `=` operator.

In [6]:
tensor = tf.Variable([2,4])
print("Original: ", tensor)

try:
    tensor[0] = 123
    print("Updated tensor using `=`: ", tensor)
except TypeError:
    print("\nTensorFlow variable can't be assigned using `=`.")

try:
    tensor[0].assign(132)
    print("Updated: ", tensor)
except TypeError:
    print("\nTernsorFlow variable can't be assigned using `assign()`")


Original:  <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 4], dtype=int32)>

TensorFlow variable can't be assigned using `=`.
Updated:  <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([132,   4], dtype=int32)>


### TensorFlow Reduce Functions

TF has a class of functions that are different from `NumPy` by starting with the `reduce_` like `reduce_sum()`, `reduce_min()`. 
This notation stems from the fact that these functions can compute a given quantity along any given axis of a tensor. 
If the axis is not specified, then the quantity is computed across all axes.

In [7]:
x = tf.random.uniform(shape=[3,5])
print(x)

print("\nCompute over all axes")
print("Min: ", tf.reduce_min(x))
print("Max: ", tf.reduce_max(x))
print("Sum: ", tf.reduce_sum(x))
print("Mean: ", tf.reduce_mean(x))

print("\nCompute for specific axis")
print("Min: ", tf.reduce_min(x, axis=1))
print("Max: ", tf.reduce_max(x, axis=0))
print("Sum: ", tf.reduce_sum(x, axis=0))
print("Mean: ", tf.reduce_mean(x, axis=1))

tf.Tensor(
[[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041]
 [0.68467236 0.74011743 0.8724445  0.22632635 0.22319686]
 [0.3103881  0.7223358  0.13318717 0.5480639  0.5746088 ]], shape=(3, 5), dtype=float32)

Compute over all axes
Min:  tf.Tensor(0.03366041, shape=(), dtype=float32)
Max:  tf.Tensor(0.8724445, shape=(), dtype=float32)
Sum:  tf.Tensor(6.9919353, shape=(), dtype=float32)
Mean:  tf.Tensor(0.466129, shape=(), dtype=float32)

Compute for specific axis
Min:  tf.Tensor([0.03366041 0.22319686 0.13318717], shape=(3,), dtype=float32)
Max:  tf.Tensor([0.68467236 0.74011743 0.8724445  0.5480639  0.5746088 ], shape=(5,), dtype=float32)
Sum:  tf.Tensor([1.6596226 1.90346   1.3585142 1.2388728 0.8314661], shape=(5,), dtype=float32)
Mean:  tf.Tensor([0.39131886 0.5493515  0.45771676], shape=(3,), dtype=float32)


### TensorFlow Indexing

In TF, data at non-consecutive indices is only achieved using the `gather()`.

In [8]:
# NumPy operations
dataCount = 24

data = np.random.uniform(low=0, high=10, size=dataCount)
print(f"Data: \n{data}\n")

indices = np.random.choice(data.shape[0], 5, replace=False)
print(f"Indices: \n{indices}\n")

print(f"Selected Data: \n{data[indices]}\n")

Data: 
[3.74540119 9.50714306 7.31993942 5.98658484 1.5601864  1.5599452
 0.58083612 8.66176146 6.01115012 7.08072578 0.20584494 9.69909852
 8.32442641 2.12339111 1.81824967 1.8340451  3.04242243 5.24756432
 4.31945019 2.9122914  6.11852895 1.39493861 2.92144649 3.66361843]

Indices: 
[ 0  5 20 15 13]

Selected Data: 
[3.74540119 1.5599452  6.11852895 1.8340451  2.12339111]



In [15]:
# TensorFlow
data = tf.random.uniform(shape=[dataCount])
print(f"Data: \n{data}\n")

indices = tf.random.uniform([5], minval=0, maxval=dataCount-1, dtype=tf.dtypes.int32)
print(f"indices: \n{indices}\n")

print("Selected data: ", tf.gather(data, indices))

Data: 
[0.5979867  0.21026528 0.84115803 0.6577226  0.2851386  0.09847593
 0.9034562  0.2376492  0.29771054 0.11016846 0.7843586  0.8114835
 0.06177711 0.68540204 0.58411586 0.11118042 0.37108076 0.2822057
 0.63202393 0.17878354 0.68082535 0.38166535 0.6973717  0.19180739]

indices: 
[ 3 19 17 12 18]

Selected data:  tf.Tensor([0.6577226  0.17878354 0.2822057  0.06177711 0.63202393], shape=(5,), dtype=float32)


In [ ]:
# Rank 2 Tensor
tensor = tf.random.normal(shape=[5,3])
print(f"Data: \n{tensor}\n")

# Indices for the data extraction
rows = tf.constant([0,2,4])
cols = tf.constant([1,2])

print(f"Selected rows: \n{tf.gather(tensor, rows, axis=0)}")
print(f"\nSelected cols: \n{tf.gather(tensor, cols, axis=1)}")

Data: 
[[-1.0249771  -0.4743215   0.12543245]
 [-0.3928874   0.5755369   0.30391353]
 [-0.359117    0.57461834 -1.0656015 ]
 [ 1.3170768  -0.6647772  -0.837381  ]
 [ 1.6496778   0.6453671   1.8788804 ]]

Selected rows: 
[[-1.0249771  -0.4743215   0.12543245]
 [-0.359117    0.57461834 -1.0656015 ]
 [ 1.6496778   0.6453671   1.8788804 ]]

Selected cols: 
[[-0.4743215   0.12543245]
 [ 0.5755369   0.30391353]
 [ 0.57461834 -1.0656015 ]
 [-0.6647772  -0.837381  ]
 [ 0.6453671   1.8788804 ]]


### TensorFlow / NumPy Interoperability

When using TensorFlow it is very common to also make use of NumPy, and it is very common to convert between NumPy and TensorFlow variables. 

NumPy to Tensor: `tf.convert_to_tensor(<numpy>)`

Tensor to NumPy: `<tensorFlow>.numpy()` 

In [25]:
pythonList = [5,7]

# Tensor from list
tensor_from_list = tf.convert_to_tensor(pythonList)

# NumPy array from Tensor
array_from_tensor = tensor_from_list.numpy()

print("Python List")
print(pythonList)
print("Tensor from List")
print(tensor_from_list)
print("NumPy from Tensor")
print(array_from_tensor)

numpyArray = np.array([12,25])
# Tensor from NumPy array
tensor_from_array = tf.convert_to_tensor(numpyArray)

# NumPy array from Tensor
array_from_tensor = tensor_from_array.numpy()

print("\nNumPy Array")
print(numpyArray)
print("Tensor from array")
print(tensor_from_array)
print("NumPy from Tensor")
print(array_from_tensor)

Python List
[5, 7]
Tensor from List
tf.Tensor([5 7], shape=(2,), dtype=int32)
NumPy from Tensor
[5 7]

NumPy Array
[12 25]
Tensor from array
tf.Tensor([12 25], shape=(2,), dtype=int64)
NumPy from Tensor
[12 25]
