In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import random

In [3]:
# Set SEED Values
SEED = 42

random.seed(SEED)
tf.random.set_seed(SEED)
np.random.seed(SEED)

In [5]:
# Tensorflow Constants
rank_0_tensor = tf.constant(3)
print(rank_0_tensor)

rank_0_tensor = tf.constant(3.141592654)
print(rank_0_tensor)

rank_0_tensor = tf.constant(3.141592654, dtype=tf.float64)
print(rank_0_tensor)

rank_1_tensor = tf.constant([2.0,3.0,4.0])
print(rank_1_tensor)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(3.1415927, shape=(), dtype=float32)
tf.Tensor(3.141592654, shape=(), dtype=float64)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


### Tensor Terminology
1. Shape: The length of each of the axes in a tensor
1. Rank: The number of tensor axes. A scalar has rank 0, vector has rank 1 
    and matrix has rank 2.
1. Axis or Dimension: The dimension of a tensor
1. Size: The total number of items in a tensor, the product of the shape vector's element. 

In [7]:
# Concatenation in Tensor is similar to NumPy
t1 = tf.constant([[1,2,3],[4,5,6]])
t2 = tf.constant([[7,8,9],[10,11,12]])

print(t1)
print(t2)
print("Concat along axis=0\n")
print(tf.concat([t1,t2],axis=0))
print("\nConcat along axis=1\n")
print(tf.concat([t1,t2], axis=1))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Concat along axis=0

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)

Concat along axis=1

tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


### TensorFlow Variables
Variables in tensorflow can only be asigned using the `assign()`, they can't be assigned using the `=` operator.

In [10]:
tensor = tf.Variable([2,4])
print("Original: ", tensor)

try:
    tensor[0] = 123
    print("Updated tensor using `=`: ", tensor)
except TypeError:
    print("\nTensorFlow variable can't be assigned using `=`.")


Original:  <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 4], dtype=int32)>

TensorFlow variable can't be assigned using `=`.


In [11]:
tensor[0].assign(132)
print("Updated: ", tensor)

Updated:  <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([132,   4], dtype=int32)>
