## NumPy Basics: Arrays vs Lists

In [1]:
import numpy as np

In [2]:
# Python List
L = [1, 2, 3]

# NumPy array
A = np.array([1, 2, 3])

In [3]:
# Iteration
print("Python List elements:")
for e in L:
    print(e)

print("NumPy Array elements:")
for e in A:
    print(e)

Python List elements:
1
2
3
NumPy Array elements:
1
2
3


In [4]:
# Appending to the list
L.append(12)
print(L)

# Appending to the array - Not possible because the size of the array is fixed.
try:
    A.append(123)
except Exception as exception:
    print("EXCEPTION: ", exception)

[1, 2, 3, 12]
EXCEPTION:  'numpy.ndarray' object has no attribute 'append'


In [5]:
# Can also append using the `+` operator
L + [5]

[1, 2, 3, 12, 5]

In [6]:
# Operations on Arrays vs Lists

# Multiplication
5 * A

array([ 5, 10, 15])

In [7]:
# On Python lists, it'll concatenate the same list that many times
5 * L

[1, 2, 3, 12, 1, 2, 3, 12, 1, 2, 3, 12, 1, 2, 3, 12, 1, 2, 3, 12]

In [8]:
# Sum
A + A

array([2, 4, 6])

In [9]:
L + L

[1, 2, 3, 12, 1, 2, 3, 12]

In [10]:
# The same operation can be achieved in NumPy using a for loop
L2 = [e * 5 for e in L]
L2

[5, 10, 15, 60]

In [11]:
# Can also apply various methods
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])