# NumPy Basics: Broadcasting

In [3]:
import numpy as np

In [4]:
A = np.array([2, 4, 6])

In [5]:
# Add value 3 to every element in the list
A + 3

array([5, 7, 9])

In [6]:
A + np.array([3])

array([5, 7, 9])

In [7]:
# To broadcast, the elements shapes should match

# If they don't, an error is thrown
A + np.array([2, 3])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [9]:
2 * A

array([ 4,  8, 12])

In [10]:
# Broadcasting when the inner dimensions of the two matrices are the same
A = np.arange(3).reshape((3, 1))
B = np.arange(2).reshape((1, 2))
print(A)
print(A.shape)

print(B)
print(B.shape)

[[0]
 [1]
 [2]]
(3, 1)
[[0 1]]
(1, 2)


In [11]:
A + B

array([[0, 1],
       [1, 2],
       [2, 3]])

#### Explanation for the above broadcasting summation

A is of size `m x n` and B is of size `n x o`. Since the inner dimentions are the same, before the summation, A is updated to be of size `m x o` and B is updated to be of size `m x o` and they are summed. 

$$
A = \begin{bmatrix}
0 \\
1 \\
2
\end{bmatrix}
\textrm {is updated to }
\begin{bmatrix}
0 & 0 \\
1 & 1 \\
2 & 2
\end{bmatrix}
$$

and 

$$
B = \begin{bmatrix}
0 & 1 
\end{bmatrix}
\textrm{is updated to }
\begin{bmatrix}
0 & 1 \\
0 & 1 \\
0 & 1 
\end{bmatrix}
$$

In [14]:
C = np.arange(3).reshape((3, 1))
D = np.arange(4).reshape((1, 4))
C + D

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])